### ISSUE TITLE
Select order print-out paper size

### ISSUE THREAD

**Issue by EIN-1** [EIN-1/My-First-Agile-Project#1]
As a **warehouse employee,** I can **select the paper size on which to print** so that **the printed label size matches the parcel size.** 

 ##  **Acceptance criteria:**

- **1. Order details include the order Id, the shipping address and the list of items in the parcel**
- **2. The warehouse employee can select the size of the order details from 3 sizes (A4,A5 and A6)**
- **3. Font size used is 12 points**

## **Tasks**

- [ ] Design a **print icon** and add it to the order details page.
- [ ] Design the **print layouts** for the different page sizes
- [ ] Create the **HTML & CSS** for the dropdown menu including the paper size
- [ ] Create the code for the model, viewer and controller
- [ ] Test the completed functionality

**Comment by EIN-1** [comment]
This is complete.

**Comment by EIN-1** [comment]
Then end 2.

**Comment by EIN-1** [comment]
ok end 3
